# Use the official Redis image as a base
FROM redis:latest

# Set the working directory to /usr/src/redis (optional)
WORKDIR /usr/src/redis

# Expose the Redis default port
EXPOSE 6379

# Start Redis server when the container starts
CMD ["redis-server"]